id: A1F0F08D6
title: Rays of Moonlight to Dispel the Darkness of Misdeeds
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:37:51.337452
  last_modified_at: 2022-03-01 00:37:51.337458
