id: A1F0F08D6
title: Method of Confession based on the Four Powers
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:37:51.335419
  last_modified_at: 2022-03-01 00:37:51.335424
